# Generated by Django 2.0.2 on 2018-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180301_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='value',
            field=models.CharField(default='default_val', max_length=1024),
        ),
    ]
