# Generated by Django 2.0.2 on 2018-03-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_field_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Field')),
            ],
        ),
        migrations.CreateModel(
            name='RiskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RiskType')),
            ],
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='riskinstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RiskInstance'),
        ),
    ]
