# Generated by Django 2.0.2 on 2018-03-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180302_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtype',
            old_name='nullable',
            new_name='required',
        ),
    ]
