# Generated by Django 2.0.2 on 2018-03-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180303_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtype',
            old_name='required',
            new_name='nullable',
        ),
    ]
