# Generated by Django 2.0.2 on 2018-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180303_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
